# Production Environment properties
# WARNING: NEVER EVER store credentials in the code base. This is a demo only!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_prod
    username: root
    password: root

server:
  port: 8080

flyway:
  locations: classpath:/db/migration/schema, classpath:/db/migration/data/production