# Dev Environment properties
# WARNING: NEVER EVER store credentials in the code base. This is a demo only!
spring:
  datasource:
    url: jdbc:h2:mem:library;mode=MySQL #jdbc:mysql://localhost:3306/library
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:/db/migration/schema, classpath:/db/migration/data/dev

server:
  port: 9000

